version: '3.7'
services:
  web.com:
    #build: web.com
    image: penan9/pythontodo_web.com
    restart: always
    ports:
      - '5001:5001'
    environment:
      - DEBUG=1
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - '80:80'
    networks:
      - flask_network

networks:
    flask_network:
